In [1]:
# import of numpy
import numpy as np
import time

In [6]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# execution calculation list vs numpy
size=10_00_00_00
pylist=list(range(size))
start_time=time.time()
sqaure=[x**2 for x in pylist]
end_time=time.time()
print(f"Python list taken time: {end_time-start_time}")

nparray=np.array(pylist)
start_time=time.time()
sqaure=nparray**2
end_time=time.time()
print(f"Numpy array taken time: {end_time-start_time}")



Python list taken time: 1.1915724277496338
Numpy array taken time: 0.18836307525634766


In [13]:
# memory
import sys
print(f"Python list size= {sys.getsizeof(pylist)*len(pylist)}")
print(f"numpy size= {nparray.nbytes}")

Python list size= 800000560000000
numpy size= 80000000


In [20]:
# creation of numpy
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype) # data-type of numpy
print(arr.shape) # tells the dimension of numpy
arr2=np.array([12,3,4,5,6,"ravi"])
print(arr2)
print(arr2.dtype) # data-type of numpy
print(arr2.shape) # tells the dimension of numpy
arr3=np.array([[1,2,3],[5,4,5],[1,2,3]])
print(arr3,arr3.shape)

[1 2 3 4 5]
int64
(5,)
['12' '3' '4' '5' '6' 'ravi']
<U21
(6,)
[[1 2 3]
 [5 4 5]
 [1 2 3]] (3, 3)


In [9]:
arr1=np.zeros((2,2),dtype="int64")
print(arr1,type(arr1),arr1.shape)
arr2=np.ones((3,2)) # by default datatype is float
print(arr2)
# 1d array
arr3=np.ones((5,))
print(arr3,arr3.shape)


[[0 0]
 [0 0]] <class 'numpy.ndarray'> (2, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[1. 1. 1. 1. 1.] (5,)


In [10]:
arr4=np.full((3,3),100)
print(arr4)

[[100 100 100]
 [100 100 100]
 [100 100 100]]
